import type { TensorType, TensorTimeReversal } from './tensorCalculator';

export interface GoldenFixture {
  group: string; // key into GENERATORS, e.g. "-3'm'"
  tensor: TensorType;
  tr: TensorTimeReversal;
  expected: string[];
  source: string;
  note?: string;
  setting?: number;
}

/**
 * Shared citation for fixtures derived directly from each group's GENERATORS entry
 * (tensorCalculator.ts) rather than transcribed from a printed table.
 *
 * Method: apply the rank-3/4 transformation law for polar (ED, EQ) and axial (MD)
 * tensors under time reversal -- Birss, "Symmetry and Magnetism" (1966), eq. 3.22
 * (polar) / 3.27 (axial) -- to the group generated by the listed generators, then
 * symmetrize the last two tensor indices. The transformation law and group-closure
 * algorithm were independently re-implemented (exact/sympy arithmetic) and verified
 * to reproduce all six pre-existing Tier-3 fixtures ('1','-1','222','mm2','4mm','32',
 * ED i-type) bit-for-bit before being applied to the groups below.
 */
const GENERATOR_DERIVATION =
  "Independently re-derived from this group's GENERATORS entry (tensorCalculator.ts) via " +
  'the rank-3/4 transformation law for polar/axial tensors under time reversal (Birss, ' +
  '"Symmetry and Magnetism" (1966), eq. 3.22 / 3.27) and last-two-index symmetrization; ' +
  're-implementation calibrated against the six pre-existing Tier-3 fixtures.';

const TABLE_4E_VERIFICATION =
  'Verified against Birss, "Symmetry and Magnetism" (1966), Table 4e (rank-3 polar ' +
  'tensor components), via the transcribed tables in `birss-tables/`. ' +
  'Table 4a maps each group to a symbol class (A_n–U_n); Table 4e gives the independent ' +
  'components for each class at rank n=3.';

/**
 * Shared citation for the ED c-type companions of the 21 Table-4e class-representative
 * fixtures above (audit Phase 3d, WORKORDER-audit-close-out.md Part 1).
 *
 * All 21 representative groups are Type-I (classical, unprimed): their GENERATORS entries
 * contain zero antiunitary elements, so closure never introduces one either (multiply()'s
 * isAntiUnitary is the XOR of its operands' flags -- XOR of false/false is always false).
 * transformTensor's `trFactor` only ever differs from +1 when `isTimeOdd && g.isAntiUnitary`;
 * with no antiunitary element in the group, that condition is never true, so trFactor is
 * unconditionally +1 regardless of tr-type. The i-type and c-type averages are therefore
 * computed by the *identical* sum for these 21 groups -- not merely equal in value but
 * literally the same computation -- independent of and prior to any app run. This is also
 * Table 7's own stated rule for the 32 classical rows ("i-tensors and c-tensors coincide for
 * classical groups"). `expected` is copied verbatim from the corresponding already
 * table-anchored ED-i fixture above.
 */
const TYPE_I_I_EQUALS_C =
  "This group's GENERATORS entry (and hence its closure) contains zero antiunitary " +
  'elements, so trFactor = 1 unconditionally (transformTensor only ever sets it to -1 when ' +
  'isTimeOdd && g.isAntiUnitary) -- the c-type average is the identical computation as the ' +
  "i-type average, not merely equal in value. Matches Table 7's own rule that i-tensors and " +
  'c-tensors coincide for the 32 classical (Type-I) rows. `expected` is copied from the ' +
  'already table-anchored ED-i fixture for this group above.';

/**
 * Shared citation for the MD i/c companions of the 11 pure-rotation (chiral) classical
 * groups (audit Phase 3d, WORKORDER-audit-close-out.md Part 1): 1, 2, 222, 4, 422, 3, 32,
 * 6, 622, 23, 432.
 *
 * Two independent structural facts, both verified directly against each group's closed
 * operator set (not against app output):
 * (a) zero antiunitary elements (as TYPE_I_I_EQUALS_C) -- i-type and c-type coincide;
 * (b) zero improper elements (det(g) = +1 for every element -- these 11 groups are exactly
 *     the chiral/pure-rotation classical point groups) -- transformTensor's `factor =
 *     (isAxial ? detG : 1) * trFactor` therefore has detG = +1 for every element regardless
 *     of the `isAxial` flag, so the ED (polar) and MD (axial) computations are the *same
 *     sum*, not merely equal in value.
 * Combined, all four of {ED,MD} x {i,c} are the identical computation for these 11 groups;
 * `expected` is copied verbatim from the already table-anchored ED-i fixture for the group.
 *
 * This also explains MD-i's achievable class range: Table 4a's "Axial tensor of odd rank n"
 * column assigns exactly these groups' own classes {A,B,D,F,H,K,L,N,P,S,T} (verified against
 * all 32 rows of table-4a.md) to every one of the 32 classical point groups -- no classical
 * group is ever assigned one of the other 10 letters {C,E,G,I,J,M,O,Q,R,U} in that column, so
 * those 10 classes are structurally unreachable for MD's i-type via *any* group, not merely
 * uncovered by this fixture set.
 */
const PURE_ROTATION_ALL_FOUR_EQUAL =
  "This group's closed operator set contains zero antiunitary elements (as " +
  'TYPE_I_I_EQUALS_C) *and* zero improper elements (det(g) = +1 for every element -- one of ' +
  'the 11 chiral/pure-rotation classical point groups), so ED-i, ED-c, MD-i, and MD-c are ' +
  'all the identical computation for this group, not merely equal in value. `expected` is ' +
  'copied from the already table-anchored ED-i fixture for this group above.';

/**
 * Shared citation for WORKORDER-fix-six-generators.md Phase 1 fixtures (the six
 * generator-set corrections: 6'/m', 6'/m, m'-3'm', m'-3'm, -4'm2', 4'/m'm'm).
 *
 * Method: from-scratch reimplementation (not imported from src/) of the rank-3
 * transformation law + group closure + basis extraction, applied to each group's
 * *corrected* GENERATORS entry -- never to app output. Calibrated bit-for-bit
 * against seven pre-existing golden fixtures before being trusted here.
 */
const SIX_GENERATOR_FIX_DERIVATION =
  "Independently re-derived (WORKORDER-fix-six-generators.md Phase 1) from this group's " +
  "*corrected* GENERATORS entry via a from-scratch reimplementation of the rank-3 " +
  'transformation law + group closure + basis extraction, calibrated bit-for-bit against ' +
  'seven pre-existing golden fixtures before being applied to these six groups; see ' +
  'docs/findings/AUDIT-convention-references.md for the derivation script and full ' +
  'calibration/cross-check log.';

export const GOLDEN_FIXTURES: GoldenFixture[] = [
  // --- Trigonal: -3'm' (Cr2O3) -----------------------------------------------------
  {
    group: "-3'm'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "The canonical magnetic-SHG group: Cr2O3 below T_N is -3'm' and this c-type ED " +
      'tensor is the textbook magnetoelectric SHG source term (Fiebig et al., JOSA B 22, ' +
      "96 (2005)). Unitary (halving) subgroup H = 32 (Birss table-6 row 82, ITC D3d(D3); " +
      "confirmed independently against the printed Birss 1962 Table 2(a) source and " +
      "cross-checked group-theoretically via M = H u theta*i*H -- see " +
      'verification-trigonal-magnetic-groups.md). For c-type ED this decomposition ' +
      "predicts -3'm'(ED,c) = 32(ED,i) = symbol class L3 (table-4e.md): " +
      'chi_zzz = 0, no xxz/zxx-family term, and the xyz-family component survives ' +
      '(group-averaged from the literal table-6 operator list, jk-presymmetrized per ' +
      "the app's own tensor convention -- see check_3mprime_v2.mjs derivation). " +
      "Previously this fixture used H = 3m (wrong -- that is -3'm's halving subgroup, " +
      "not -3'm''s) and asserted the M3 form instead; fixed alongside the -3'm' " +
      'generator correction (symmetryGroups.ts). Independently confirmed against the ' +
      'primary source itself (Fiebig, Pavlov, Pisarev, JOSA B 22, 96 (2005), Sec. ' +
      '4.A.3, p.100, citing Birss): "chi^e(c) === chi_yyy = -chi_yxx = -chi_xyx = ' +
      '-chi_xxy, chi_xyz = chi_xzy = -chi_yxz = -chi_yzx" -- an exact match to this ' +
      'fixture and a direct contradiction of the old M3 form.',
  },
  {
    group: "-3'm'",
    tensor: 'MD',
    tr: 'i',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "Axial-tensor branch for the Cr2O3 group. i-type results depend only on the " +
      "group's rotation parts (trFactor = 1 regardless of isAntiUnitary for i-type), so " +
      "-3'm'(MD,i) = -3m(MD,i); this matches the existing '32' ED i-type golden fixture " +
      'form, reflecting that axial i-tensors of -3m equal polar i-tensors of its proper ' +
      'rotation subgroup 32.',
  },

  // --- Hexagonal: 6'mm' / 6m'm' (magnetic phases of 6mm, e.g. hexagonal manganites) -
  {
    group: "6'mm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "i-type results depend only on the rotation parts, so 6'mm'(ED,i) = 6mm(ED,i) " +
      '(same form as the existing 4mm i-type golden fixture).',
  },
  {
    group: "6'mm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: GENERATOR_DERIVATION,
    note: "c-type SHG tensor for the 6'mm' magnetic phase of hexagonal manganites (e.g. some RMnO3 magnetic structures).",
  },
  {
    group: "6m'm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so 6m'm'(ED,i) = 6mm(ED,i), same as 6'mm'(ED,i).",
  },
  {
    group: "6m'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note:
      "c-type SHG tensor for the 6m'm' magnetic phase -- distinct from 6'mm'(ED,c) " +
      'above, pinning down which mirror carries the prime.',
  },

  // --- Triclinic family: -1' -------------------------------------------------------
  {
    group: "-1'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxx}',
      '\\chi_{xxy} = \\chi_{xyx}',
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyy}',
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{xzz}',
      '\\chi_{yxx}',
      '\\chi_{yxy} = \\chi_{yyx}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyy}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{yzz}',
      '\\chi_{zxx}',
      '\\chi_{zxy} = \\chi_{zyx}',
      '\\chi_{zxz} = \\chi_{zzx}',
      '\\chi_{zyy}',
      '\\chi_{zyz} = \\chi_{zzy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note:
      "Triclinic Type-III family check. -1' = {1, i*theta} (inversion combined with " +
      'time reversal, no plain inversion). For c-type ED, every group element acts as ' +
      '+1 on the rank-3 tensor (the parity flip from inversion cancels the c-type sign ' +
      'flip), so all 18 last-two-index-symmetrized components survive independently -- ' +
      "the same count/shape as the existing point-group '1' fixture.",
  },

  // --- Monoclinic family: 2'/m' -----------------------------------------------------
  {
    group: "2'/m'",
    tensor: 'MD',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}',
      '\\chi_{zxy} = \\chi_{zyx}',
      '\\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Monoclinic Type-III family check (axial branch, mirror plane normal to z carries the prime).",
  },

  // --- Orthorhombic family: m'm'm / m'm'2 --------------------------------------------
  {
    group: "m'm'm",
    tensor: 'MD',
    tr: 'c',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}',
      '\\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Orthorhombic Type-III family check, centrosymmetric member (axial c-type branch). TABLE_4E_VERIFICATION is scoped to rank-3 polar (ED) components only, so this axial (MD) fixture stays generator-derived.",
  },
  {
    group: "m'm'2",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{zxy} = \\chi_{zyx}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Orthorhombic Type-III family check, polar member (c-type ED SHG tensor).',
  },

  // --- Tetragonal family: 4'mm' / 4/m'm'm' -------------------------------------------
  {
    group: "4'mm'",
    tensor: 'ED',
    tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so 4'mm'(ED,i) = 4mm(ED,i), matching the existing 4mm golden fixture exactly.",
  },
  {
    group: "4'mm'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}',
      '\\chi_{zxx} = -\\chi_{zyy}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Tetragonal Type-III family check, polar member (c-type ED SHG tensor).',
  },
  {
    group: "4'mm'",
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Axial i-type branch for the same group, exercising the det(g) factor for a Type-III group.',
  },
  {
    group: "4/m'm'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Tetragonal Type-III family check, centrosymmetric member (c-type ED SHG tensor).',
  },

  // --- Trigonal family (additional members): 32' / 3m' ------------------------------
  {
    group: "32'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}',
      '\\chi_{zzz}',
    ],
    source: GENERATOR_DERIVATION,
    note: "Additional trigonal Type-III coverage alongside -3'm'.",
  },
  {
    group: "3m'",
    tensor: 'ED',
    tr: 'c',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Trigonal polar Type-III member (c-type ED SHG tensor).',
  },

  // --- Hexagonal family (centrosymmetric member): 6/m'm'm' --------------------------
  {
    group: "6/m'm'm'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Hexagonal Type-III family check, centrosymmetric member (c-type ED SHG tensor).',
  },

  // --- Cubic family: m'-3' / 4'32' ------------------------------------------------------
  {
    group: "m'-3'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: 'Cubic Type-III family check (c-type ED SHG tensor) -- the single fully-antisymmetric-index cubic invariant.',
  },
  {
    group: "m'-3'",
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: "i-type results depend only on the rotation parts, so m'-3'(MD,i) = m-3(MD,i), the cubic axial-tensor analogue of the relation above.",
  },
  {
    group: "4'32'",
    tensor: 'ED',
    tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: GENERATOR_DERIVATION,
    note: "Additional cubic Type-III coverage -- a different generator combination (chiral 432-based) reduces to the same invariant as m'-3'(ED,c).",
  },

  // --- MD (axial, i-type) coverage for Type-I groups ---------------------------------
  {
    group: '4/mmm',
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Exercises the det(g) axial branch of transformTensor() for a Type-I tetragonal group.',
  },
  {
    group: '622',
    tensor: 'MD',
    tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: GENERATOR_DERIVATION,
    note: 'Exercises the det(g) axial branch of transformTensor() for a Type-I hexagonal group.',
  },
  {
    group: 'm-3m',
    tensor: 'MD',
    tr: 'i',
    expected: ['All components are zero.'],
    source: GENERATOR_DERIVATION,
    note: "Cubic m-3m has no non-zero axial rank-3 invariant (its mirrors forbid the m'-3'-style fully-antisymmetric form), unlike the lower-symmetry groups above -- a useful negative case for the det(g) branch.",
  },

  // --- EQ (rank-4) coverage ------------------------------------------------------------
  {
    group: 'm-3m',
    tensor: 'EQ',
    tr: 'i',
    expected: [
      '\\chi_{xxxx} = \\chi_{yyyy} = \\chi_{zzzz}',
      '\\chi_{xxyy} = \\chi_{xxzz} = \\chi_{yyxx} = \\chi_{yyzz} = \\chi_{zzxx} = \\chi_{zzyy}',
      '\\chi_{xyxy} = \\chi_{xyyx} = \\chi_{xzxz} = \\chi_{xzzx} = \\chi_{yxxy} = \\chi_{yxyx} = \\chi_{yzyz} = \\chi_{yzzy} = \\chi_{zxxz} = \\chi_{zxzx} = \\chi_{zyyz} = \\chi_{zyzy}',
    ],
    source: GENERATOR_DERIVATION,
    note: 'Rank-4 EQ fixture for the highest-symmetry cubic group: three independent invariants (the cubic analogue of the elastic constants C11/C12/C44 pattern, here without Voigt symmetry between the two middle indices).',
  },

  // =============================================================================
  // Birss Table 4e verification: all 21 symbol classes at rank 3 (ED i-type)
  // One representative group per symbol class (A_n through U_n).
  // =============================================================================

  {
    group: '1', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx}', '\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xxz} = \\chi_{xzx}',
      '\\chi_{xyy}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{xzz}',
      '\\chi_{yxx}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{yyy}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{yzz}',
      '\\chi_{zxx}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zxz} = \\chi_{zzx}',
      '\\chi_{zyy}', '\\chi_{zyz} = \\chi_{zzy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row A3 (18 independent components).',
  },
  {
    group: '2', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyz} = \\chi_{xzy}',
      '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row B3 (8 independent components).',
  },
  {
    group: 'm', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx}', '\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyy}', '\\chi_{xzz}',
      '\\chi_{yxx}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyy}', '\\chi_{yzz}',
      '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyz} = \\chi_{zzy}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row C3 (10 independent components).',
  },
  {
    group: '222', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row D3 (3 independent components).',
  },
  {
    group: 'mm2', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row E3 (5 independent components).',
  },
  {
    group: '4', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row F3 (4 independent components).',
  },
  {
    group: '-4', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}',
      '\\chi_{zxx} = -\\chi_{zyy}', '\\chi_{zxy} = \\chi_{zyx}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row G3 (4 independent components).',
  },
  {
    group: '422', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row H3 (1 independent component).',
  },
  {
    group: '4mm', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row I3 (3 independent components).',
  },
  {
    group: '-42m', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row J3 (2 independent components).',
  },
  {
    group: '3', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row K3 (6 independent components).',
  },
  {
    group: '32', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row L3 (2 independent components).',
  },
  {
    group: '3m', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row M3 (4 independent components).',
  },
  {
    group: '6', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}',
      '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}',
      '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row N3 (4 independent components).',
  },
  {
    group: '-6', tensor: 'ED', tr: 'i',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
    ],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row O3 (2 independent components).',
  },
  {
    group: '622', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row P3 (1 independent component).',
  },
  {
    group: '6mm', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row Q3 (3 independent components).',
  },
  {
    group: '-6m2', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row R3 (1 independent component).',
  },
  {
    group: '23', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row S3 (1 independent component).',
  },
  {
    group: '432', tensor: 'ED', tr: 'i',
    expected: ['All components are zero.'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row T3 (all zero — piezoelectricity forbidden in 432).',
  },
  {
    group: '-43m', tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: TABLE_4E_VERIFICATION,
    note: 'Birss Table 4e row U3 (1 independent component).',
  },

  // ED c-type companions of the 21 Table-4e class-representative fixtures above (audit
  // Phase 3d): each group's GENERATORS entry contains zero antiunitary elements, so the
  // c-type value is the identical computation as the already table-anchored i-type value
  // -- see TYPE_I_I_EQUALS_C.
  {
    group: "1", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx}", "\\chi_{xxy} = \\chi_{xyx}", "\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyy}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{xzz}", "\\chi_{yxx}", "\\chi_{yxy} = \\chi_{yyx}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyy}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{yzz}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zxz} = \\chi_{zzx}", "\\chi_{zyy}", "\\chi_{zyz} = \\chi_{zzy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row A3 (18 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "2", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row B3 (8 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "m", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx}", "\\chi_{xxy} = \\chi_{xyx}", "\\chi_{xyy}", "\\chi_{xzz}", "\\chi_{yxx}", "\\chi_{yxy} = \\chi_{yyx}", "\\chi_{yyy}", "\\chi_{yzz}", "\\chi_{zxz} = \\chi_{zzx}", "\\chi_{zyz} = \\chi_{zzy}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row C3 (10 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "222", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{zxy} = \\chi_{zyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row D3 (3 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "mm2", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx}", "\\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row E3 (5 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "4", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row F3 (4 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "-4", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}", "\\chi_{zxx} = -\\chi_{zyy}", "\\chi_{zxy} = \\chi_{zyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row G3 (4 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "422", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row H3 (1 independent component) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "4mm", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row I3 (3 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "-42m", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}", "\\chi_{zxy} = \\chi_{zyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row J3 (2 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "3", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}", "\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row K3 (6 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "32", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row L3 (2 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "3m", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}", "\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row M3 (4 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "6", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row N3 (4 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "-6", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}", "\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row O3 (2 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "622", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row P3 (1 independent component) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "6mm", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row Q3 (3 independent components) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "-6m2", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row R3 (1 independent component) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "23", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row S3 (1 independent component) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "432", tensor: 'ED', tr: 'c',
    expected: ["All components are zero."],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row T3 (all zero — piezoelectricity forbidden in 432) -- same class as the ED-i fixture for this group above.',
  },
  {
    group: "-43m", tensor: 'ED', tr: 'c',
    expected: ["\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}"],
    source: TYPE_I_I_EQUALS_C,
    note: 'Birss Table 4e row U3 (1 independent component) -- same class as the ED-i fixture for this group above.',
  },

  // MD i/c companions of the pure-rotation-group subset of the Table-4e class
  // representatives above (audit Phase 3d): these 11 groups (1, 2, 222, 4, 422, 3, 32,
  // 6, 622, 23, 432) are the *only* classical point groups that are pure rotation
  // (chiral, zero improper elements) -- see PURE_ROTATION_ALL_FOUR_EQUAL. They are also
  // the only 11 classes structurally reachable by MD's i-type at all: Table 4a's
  // "Axial tensor of odd rank n" column only ever assigns one of exactly these 11
  // letters {A,B,D,F,H,K,L,N,P,S,T} to any of the 32 classical point groups (verified
  // against the full table); the other 10 letters {C,E,G,I,J,M,O,Q,R,U} never appear in
  // that column and so can never be an MD-i class for *any* group. MD-i class coverage
  // is therefore complete at 11/11 achievable classes, not merely time-boxed.
  {
    group: "1", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxx}", "\\chi_{xxy} = \\chi_{xyx}", "\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyy}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{xzz}", "\\chi_{yxx}", "\\chi_{yxy} = \\chi_{yyx}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyy}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{yzz}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zxz} = \\chi_{zzx}", "\\chi_{zyy}", "\\chi_{zyz} = \\chi_{zzy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row A3 (18 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "1", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxx}", "\\chi_{xxy} = \\chi_{xyx}", "\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyy}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{xzz}", "\\chi_{yxx}", "\\chi_{yxy} = \\chi_{yyx}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyy}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{yzz}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zxz} = \\chi_{zzx}", "\\chi_{zyy}", "\\chi_{zyz} = \\chi_{zzy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row A3 (18 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "2", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row B3 (8 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "2", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxz} = \\chi_{xzx}", "\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{yyz} = \\chi_{yzy}", "\\chi_{zxx}", "\\chi_{zxy} = \\chi_{zyx}", "\\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row B3 (8 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "222", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{zxy} = \\chi_{zyx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row D3 (3 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "222", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xyz} = \\chi_{xzy}", "\\chi_{yxz} = \\chi_{yzx}", "\\chi_{zxy} = \\chi_{zyx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row D3 (3 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "4", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row F3 (4 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "4", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row F3 (4 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "422", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row H3 (1 independent component) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "422", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row H3 (1 independent component) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "3", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}", "\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row K3 (6 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "3", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}", "\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row K3 (6 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "32", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row L3 (2 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "32", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row L3 (2 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "6", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row N3 (4 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "6", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}", "\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}", "\\chi_{zxx} = \\chi_{zyy}", "\\chi_{zzz}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row N3 (4 independent components) -- same class and value as the ED-i fixture for this group above.',
  },
  // 622 MD-i already pinned above (Table 4e row P3, Type-I hexagonal det(g) branch);
  // this constant additionally confirms it equals the ED-i value (PURE_ROTATION_ALL_FOUR_EQUAL).
  {
    group: "622", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row P3 (1 independent component) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "23", tensor: 'MD', tr: "i",
    expected: ["\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row S3 (1 independent component) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "23", tensor: 'MD', tr: "c",
    expected: ["\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}"],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row S3 (1 independent component) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "432", tensor: 'MD', tr: "i",
    expected: ["All components are zero."],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row T3 (all zero — piezoelectricity forbidden in 432) -- same class and value as the ED-i fixture for this group above.',
  },
  {
    group: "432", tensor: 'MD', tr: "c",
    expected: ["All components are zero."],
    source: PURE_ROTATION_ALL_FOUR_EQUAL,
    note: 'Birss Table 4e row T3 (all zero — piezoelectricity forbidden in 432) -- same class and value as the ED-i fixture for this group above.',
  },

  // Alternate-setting fixtures — Phase 1 (Mechanism B, setting 2)
  // Similarity transform S·G·S⁻¹ swaps σ_v ↔ σ_d mirror families.
  // i-type tensors are identical between settings (Mechanism B);
  // only c-type tensors differ — the component families swap.
  {
    group: "4'mm'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: 'Similarity transform Rz(45°) applied to base generators; c-type family swaps from d₁₅-type to d₁₄-type.',
  },
  {
    group: "4'22'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: 'Similarity transform Rz(45°); swaps d₁₄→d₁₅ family.',
  },
  {
    group: "6'mm'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}'],
    source: 'Similarity transform Rz(30°); swaps d₁₁→d₂₂ family.',
  },
  {
    group: "6'22'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: 'Similarity transform Rz(30°); swaps d₂₂→d₁₁ family.',
  },
  {
    group: "6'/mm'm", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}'],
    source: 'Similarity transform Rz(30°); swaps d₁₁→d₂₂ family.',
  },

  // Alternate-setting fixtures — Phase 2, Mechanism A (classical setting ambiguity)
  // Rz(45°/30°) swaps ⟨100⟩ ↔ ⟨110⟩ (tetragonal) or ⟨100⟩ ↔ ⟨210⟩ (trigonal/hexagonal).
  // Both i-type and c-type may differ (the swap changes the spatial element assignment).

  // Tetragonal Mechanism A — Rz(45°)
  {
    group: "-4'2m'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: 'Similarity transform Rz(45°); swaps d₁₄→d₁₅ family (i-type).',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "-4'm2'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source:
      "Birss Table 7 (class lookup) + Table 4e row J3, jk-particularized. Re-anchored " +
      "after the -4'm2' generator fix (symmetryGroups.ts, WORKORDER-fix-six-generators.md " +
      "Phase 2): Default and Setting 2 swap frames. Setting 2 (Rz(45°)) now carries the " +
      "'-42m'-diagonal-mirror orientation -- IDENTICAL to the standalone '-42m' ED-i golden " +
      "fixture above (Birss Table 4e row J3, 2 independent components) -- while Default " +
      "carries the '-4m2'-axis form (see the -4'm2' Default ED-i fixture, Phase 1e, " +
      "WORKORDER-fix-six-generators.md). Previously this entry was pinned (wrongly) to the " +
      "'-4m2'-axis form under a 'similarity transform Rz(45°)' citation -- that anchor was " +
      'app-derived (not admissible) and predates the fix.',
  },
  {
    group: "-42'm'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: 'Similarity transform Rz(45°); swaps d₁₄→d₁₅ family (i-type).',
  },
  {
    group: "-42'm'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: 'Similarity transform Rz(45°); swaps d₁₅→d₁₄ family (c-type).',
  },

  // Trigonal Mechanism A — Rz(30°)
  {
    group: "32'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: 'Similarity transform Rz(30°); swaps d₂₂→d₁₁ plus d₁₄ families.',
  },
  {
    group: "32'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}', '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Similarity transform Rz(30°); c-type acquires 3m-like 4-component tensor.',
  },
  {
    group: "3m'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}', '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Similarity transform Rz(30°); i-type acquires 3m-like 4-component tensor.',
  },
  {
    group: "3m'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: 'Similarity transform Rz(30°); c-type acquires 32-like 2-component tensor.',
  },
  {
    group: "-3'm", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}', '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Similarity transform Rz(30°); c-type acquires 3m-like 4-component tensor.',
  },
  {
    group: "-3'm'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: "Similarity transform Rz(30°) applied to the corrected (H=32, symbol class L3) setting-1 form; matches the \"3m'\" setting-2 fixture's form exactly, as expected since both reduce to an i-type-of-32 relation.",
  },
  {
    group: "-3m'", tensor: 'MD', tr: 'i', setting: 1,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: "Fiebig et al., JOSA B 22, 96 (2005), Sec. 3, chi^{m(i)} for Cr2O3 (their 3-bar-m' = -3'm', anchored to Birss ref. 50): chi_yyy = -chi_yxx = -chi_xyx = -chi_xxy and chi_xyz = chi_xzy = -chi_yxz = -chi_yzx. MD-i is time-even, so it depends only on the spatial symmetry -3m, which -3'm' and -3m' share; the form is identical for -3m'. The yyy-family (mirror perpendicular to y) fixes the standard setting; a 30deg-rotated setting gives the xxx-family.",
    // VERIFY: pending human sign-off against Fiebig et al. (2005) / printed Birss tables.
  },
  {
    group: "-3m'", tensor: 'MD', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: "Rz(30deg) rotation of the Fiebig/Birss-anchored -3m' MD-i default form above into the -31m' setting. Pure tensor algebra; verified to reproduce the app's transformed-operator projection.",
    // VERIFY: pending human sign-off against Fiebig et al. (2005) / printed Birss tables.
  },

  // Hexagonal Mechanism A — Rz(30°)
  {
    group: "-6'2m'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: 'Similarity transform Rz(30°); swaps d₂₂→d₁₁ family. Table-7 cross-check: (-6\'2m\') i-tensor polar odd = R_n, consistent with 1 independent component.',
  },
  {
    group: "-6'm2'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}'],
    source: 'Similarity transform Rz(30°); swaps d₁₁→d₂₂ family.',
  },
  {
    group: "-6m'2'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}'],
    source: 'Similarity transform Rz(30°); swaps d₁₁→d₂₂ family.',
  },
  {
    group: "-6m'2'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}'],
    source: 'Similarity transform Rz(30°); swaps d₂₂→d₁₁ family (c-type).',
  },

  // Alternate-setting fixtures — Phase 2, Orthorhombic axis orientation
  // Cyclic permutation (setting 2 = a-unique) and reverse cyclic (setting 3 = b-unique).
  // Table-7 cross-check: (2'm'm) i-tensor polar odd = (E_n), 5 components — consistent.
  {
    group: "2'2'2", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: 'Cyclic axis permutation; c-type acquires mm2-like tensor with x as unique axis.',
  },
  {
    group: "2'2'2", tensor: 'ED', tr: 'c', setting: 3,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Reverse cyclic axis permutation; c-type acquires mm2-like tensor with y as unique axis.',
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: TABLE_4E_VERIFICATION,
    note: "Corrected Default (setting 1), Birss Table 6 orientation {1, m_z, 2'_x, m'_y}; i-tensor sits x-unique.",
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'c',
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: TABLE_4E_VERIFICATION,
    note: "Corrected Default (setting 1), Birss Table 6 orientation {1, m_z, 2'_x, m'_y}; c-tensor sits y-unique.",
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: TABLE_4E_VERIFICATION,
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'i', setting: 3,
    expected: ['\\chi_{xxz} = \\chi_{xzx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: TABLE_4E_VERIFICATION,
  },
  {
    group: "2'm'm", tensor: 'ED', tr: 'c', setting: 3,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: TABLE_4E_VERIFICATION,
  },
  {
    group: "m'm'2", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: 'Cyclic axis permutation; i-type rotates to a-unique.',
  },
  {
    group: "m'm'2", tensor: 'ED', tr: 'i', setting: 3,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Reverse cyclic axis permutation; i-type rotates to b-unique.',
  },
  {
    group: "mmm'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: TABLE_4E_VERIFICATION,
  },
  {
    group: "mmm'", tensor: 'ED', tr: 'c', setting: 3,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: TABLE_4E_VERIFICATION,
  },

  // Alternate-setting fixtures — Phase 2, Monoclinic axis choice (z→b unique)
  // MONO_YZ_SWAP swaps y↔z (with x-flip for det=+1), converting z-unique (Birss) to b-unique (ITC).
  {
    group: "2'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxx}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Monoclinic y↔z swap; i-type rotates 2-fold from z to y (b-unique ITC convention).',
  },
  {
    group: "2'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Monoclinic y↔z swap; c-type rotates m from ⊥z to ⊥y (b-unique ITC convention).',
  },
  {
    group: "m'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Monoclinic y↔z swap; i-type rotates mirror normal from z to y (b-unique ITC convention).',
  },
  {
    group: "m'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxx}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Monoclinic y↔z swap; c-type rotates 2-fold from z to y.',
  },
  {
    group: "2'/m", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Monoclinic y↔z swap; c-type rotates mirror normal from z to y (b-unique ITC convention).',
  },
  {
    group: "2/m'", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxx}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Monoclinic y↔z swap; c-type rotates 2-fold from z to y.',
  },

  // --- B1: Type I (colourless) alternate-setting fixtures ---
  // Mechanism A (classical setting ambiguity) — Rz(45°/30°)
  {
    group: '-42m', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: 'Birss Table 4a: -42m (J_n) → -4m2 orientation via Rz(45°). Verified: d₁₅-type form (xxz/yyz antisymmetric).',
  },
  {
    group: '32', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: 'Birss Table 4a: 32 (L_n, 2//y) → 312 orientation via Rz(30°). Swaps d₂₂→d₁₁ family.',
  },
  {
    group: '3m', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}', '\\chi_{xxz} = \\chi_{xzx} = \\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx} = \\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Birss Table 4a: 3m (M_n, -2//y) → 31m orientation via Rz(30°). Swaps d₁₁→d₂₂ family.',
  },
  {
    group: '-6m2', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}'],
    source: 'Birss Table 4a: -6m2 (R_n) → -62m orientation via Rz(30°). Swaps d₁₁→d₂₂ family.',
  },

  // Orthorhombic axis orientation (cyclic/reverse permutation)
  {
    group: 'mm2', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: 'Birss Table 4a: mm2 (E_n) → 2mm orientation via ORTHO_CYCLIC (axis cycle x→y→z).',
  },
  {
    group: '222', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: 'Birss Table 4a: 222 (D_n) → axis permutation via ORTHO_CYCLIC. D_n form (3 xyz-family components) is invariant under axis permutation.',
  },
  {
    group: 'm', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xxz} = \\chi_{xzx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{yyz} = \\chi_{yzy}', '\\chi_{zxx}', '\\chi_{zxz} = \\chi_{zzx}', '\\chi_{zyy}', '\\chi_{zzz}'],
    source: 'Birss Table 4a: m (C_n, -2//z) → b-unique (ITC, -2//y) via MONO_YZ_SWAP.',
  },
  {
    group: 'mm2', tensor: 'ED', tr: 'i', setting: 3,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{yxx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Birss Table 4a: mm2 (E_n) → m2m orientation via ORTHO_REVERSE (reverse axis cycle).',
  },

  // Monoclinic axis choice (z-unique Birss → b-unique ITC)
  {
    group: '2', tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxx}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Birss Table 4a: 2 (B_n, 2//z) → b-unique (ITC, 2//y) via MONO_YZ_SWAP.',
  },

  // --- B1: Type II (grey) — i-type must equal colourless parent ---
  {
    group: "-42m1'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: 'Grey derivative of -42m: i-type equals colourless parent (ε preserved through S·G·S⁻¹).',
  },
  {
    group: "321'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}', '\\chi_{xyz} = \\chi_{xzy} = -\\chi_{yxz} = -\\chi_{yzx}'],
    source: 'Grey derivative of 32: i-type equals colourless parent.',
  },
  {
    group: "mm21'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxx}', '\\chi_{xyy}', '\\chi_{xzz}', '\\chi_{yxy} = \\chi_{yyx}', '\\chi_{zxz} = \\chi_{zzx}'],
    source: 'Grey derivative of mm2: i-type equals colourless parent.',
  },
  {
    group: "21'", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['\\chi_{xxy} = \\chi_{xyx}', '\\chi_{xyz} = \\chi_{xzy}', '\\chi_{yxx}', '\\chi_{yxz} = \\chi_{yzx}', '\\chi_{yyy}', '\\chi_{yzz}', '\\chi_{zxy} = \\chi_{zyx}', '\\chi_{zyz} = \\chi_{zzy}'],
    source: 'Grey derivative of 2: i-type equals colourless parent.',
  },

  // =============================================================================
  // WORKORDER-fix-six-generators.md Phase 1 -- golden fixtures for the six generator-set
  // corrections: 6'/m', 6'/m, m'-3'm', m'-3'm, -4'm2', 4'/m'm'm.
  // VERIFIED: all ten fixtures below signed off against printed Birss Table 4e (2026-07-02); see AGENTS.md.
  //
  // Expected values are independently re-derived -- never read off app output -- via a
  // from-scratch reimplementation of the rank-3 transformation law + group closure + basis
  // extraction (mirroring tensorProjection.ts but written separately), applied to each
  // group's *corrected* GENERATORS entry (the Phase 2 fix in symmetryGroups.ts). The
  // reimplementation was calibrated bit-for-bit against seven pre-existing golden fixtures
  // (-3'm' ED c / MD i, default -42m ED i, 4mm ED i, m-3m MD i, -43m ED i, 432 ED i) before
  // being trusted on these six groups; several of the values below also land on an exact
  // textual match with an independently-cited pre-existing fixture elsewhere in this file
  // (noted per-entry). See docs/findings/AUDIT-convention-references.md for the derivation
  // script and full calibration/cross-check log.
  // =============================================================================
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "6'/m'", tensor: 'ED', tr: 'i',
    expected: ['All components are zero.'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "H (unitary halving subgroup) = C3i, and crucially the group's inversion is the " +
      "UNITARY '-1' (table-nomenclature.md row \"C6h(C3i) | 6'/m'\": operator column is " +
      "`1, -1, ±3_z, ±-3_z, 2'_z, -2'_z, ±6'_z, ±-6'_z` -- bare `-1`, not `-1'`). i-type " +
      'ignores the antiunitary flag entirely, so any spatially-inversive element -- unitary ' +
      'or primed -- forces all polar (ED) odd-rank tensors to zero by parity.',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "6'/m'", tensor: 'ED', tr: 'c',
    expected: ['All components are zero.'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      'The same UNITARY inversion kills c-type too: for a unitary (non-antiunitary) ' +
      'element, trFactor is always +1 regardless of tr-type, so a unitary -1 forces T = -T ' +
      'for any polar rank-3 T, independent of time-reversal weighting. This is the bug this ' +
      "fixture catches: pre-fix, the app has the primed/unprimed inversion flags swapped " +
      "between this group and 6'/m, so the OLD \"6'/m'\" generators give this group the " +
      "nonzero 6'/m answer (Birss Table 4e row O3, see the 6'/m ED-c fixture below) instead " +
      'of zero.',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "6'/m", tensor: 'ED', tr: 'i',
    expected: ['All components are zero.'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      'i-type strips the antiunitary flag, so it sees the full 12-element spatial operation ' +
      'set (H = C3h union its primed-inversion coset), which spatially equals the full ' +
      'centrosymmetric 6/m (C6h) point group -- forcing ED-i = 0 by parity, independent of ' +
      'the time-reversal bug fixed here.',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "6'/m", tensor: 'ED', tr: 'c',
    expected: [
      '\\chi_{xxx} = -\\chi_{xyy} = -\\chi_{yxy} = -\\chi_{yyx}',
      '\\chi_{xxy} = \\chi_{xyx} = \\chi_{yxx} = -\\chi_{yyy}',
    ],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "H (unitary halving subgroup) = C3h = the standalone '-6' point group " +
      "(table-nomenclature.md row \"C6h(C3h) | 6'/m\": unitary part `1, -2_z, ±3_z, ±-6_z`). " +
      'c-type weights H at +1 and its primed-inversion coset at -1; the surviving ' +
      "2-component space is IDENTICAL to '-6'(ED,i) -- Birss Table 4e row O3, an " +
      'independently-cited golden fixture already in this file above (\'-6\', ED, i) -- an ' +
      'exact textual match, not merely a structural analogy. This is the decisive fixture ' +
      "for the swap bug: pre-fix, the app's primed-inversion flag is backwards between " +
      "6'/m' and 6'/m (same bug as the pair above), so the OLD \"6'/m\" generators give the " +
      '(wrong) all-zero answer instead of this form.',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "m'-3'm'", tensor: 'ED', tr: 'c',
    expected: ['All components are zero.'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "H (unitary halving subgroup) = 432 (O point group; table-nomenclature.md row " +
      "\"Oh(O) | m'-3'm'\": unitary part `1, 9(2), 4(±3), 3(±4)`, order 24). Even the " +
      'H-only (weight-+1) polar rank-3 invariant space is already the zero subspace -- ' +
      "Birss Table 4e row T3, 'piezoelectricity forbidden in 432', an independently-cited " +
      "golden fixture already in this file above ('432', ED, i) -- so intersecting with the " +
      "c-type +/-1 weighting (necessarily a subspace of the H-invariant space) stays zero " +
      "regardless of the antiunitary coset's sign.",
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "m'-3'm", tensor: 'ED', tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx} = \\chi_{zxy} = \\chi_{zyx}'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "H (unitary halving subgroup) = -43m (Td point group; table-nomenclature.md row " +
      "\"Oh(Td) | m'-3'm\": unitary part `1, 3(2), 6(-2), 4(±3), 3(±-4)`, order 24). The " +
      'surviving c-type space equals the full H-invariant space -- Birss Table 4e row U3 ' +
      "(1 independent component), IDENTICAL to the standalone '-43m' ED-i golden fixture " +
      'already in this file above: an exact textual match. This is the decisive fixture for ' +
      "the m'-3'm'/m'-3'm swap bug: pre-fix, the app gives this Td-type single-component " +
      "form to \"m'-3'm'\" (H = O, where it must be zero per the entry above) instead of to " +
      "\"m'-3'm\".",
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "-4'm2'", tensor: 'ED', tr: 'i',
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      'H (unitary halving subgroup) = mm2 (z-unique, mirrors perp-x/perp-y; ' +
      "table-nomenclature.md row \"D2d(C2v) | -4'm2'\": unitary part `1, 2_z, -2_x, -2_y`). " +
      'i-type ignores the antiunitary flag and averages over the full 8-element spatial ' +
      "set, which equals the '-4m2' orientation of D2d (mirrors perp-x/perp-y, as opposed " +
      "to the default '-42m' diagonal-mirror setting) -- IDENTICAL to the existing '-42m' " +
      "setting-2 (Rz(45 deg), the '-4m2' orientation) ED-i golden fixture already in this " +
      "file: an exact textual match. This is the decisive Default-frame fixture for the " +
      "-4'm2' bug: pre-fix, the app builds the Default generators in the Rz(45 deg)-rotated " +
      "('-42m'-diagonal) frame instead, so this form was wrongly pinned to Setting 2 (see " +
      'the Phase 3 re-anchor of the line-570 fixture) while Default gave the other ' +
      "('-42m'-class) form.",
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "4'/m'm'm", tensor: 'ED', tr: 'i',
    expected: ['All components are zero.'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "Guard fixture (WORKORDER-fix-six-generators.md Phase 1f): i-type strips the " +
      'antiunitary flag, seeing the full 16-element spatial set = the centrosymmetric ' +
      '4/mmm point group -- forcing ED-i = 0 regardless of the frame-orientation bug fixed ' +
      'here. Passes both pre- and post-fix (orientation-independent); kept as a guard only, ' +
      'not the decisive pin (see the ED-c entry below).',
  },
  // VERIFIED: expected values signed off against printed Birss Table 4e (2026-07-02).
  {
    group: "4'/m'm'm", tensor: 'ED', tr: 'c',
    expected: ['\\chi_{xyz} = \\chi_{xzy} = \\chi_{yxz} = \\chi_{yzx}', '\\chi_{zxy} = \\chi_{zyx}'],
    source: SIX_GENERATOR_FIX_DERIVATION,
    note:
      "H (unitary halving subgroup) = -42m (D2d, standard diagonal-mirror setting; " +
      "table-nomenclature.md row \"D4h(D2d) | 4'/m'm'm\": unitary part `1, 2_x, 2_y, 2_z, " +
      '-2_xy, -2_-xy, ±-4_z`, IDENTICAL to the standalone GENERATORS[\'-42m\'] group). ' +
      'c-type weights H at +1 and the primed-inversion coset at -1; the surviving space ' +
      "equals the full '-42m'-default ED-i space (Birss Table 4e row J3) -- an exact " +
      "textual match to the standalone '-42m' ED-i golden fixture already in this file. " +
      'DEVIATION FROM WORKORDER: WORKORDER-fix-six-generators.md Phase 1f names "MD c" as ' +
      'the decisive pin and claims "ED i ≡ 0 and c ≡ 0". Independent re-derivation ' +
      '(calibrated separately -- see docs/findings/AUDIT-convention-references.md) shows ' +
      'this is incorrect on two points: (1) MD-c is identically zero for this group (the ' +
      'antiunitary -1’ imposes T = -T on the axial c-type tensor via the extra det(g) ' +
      'factor, unlike the polar case), so a zero, frame-invariant tensor cannot be the ' +
      'frame-sensitive discriminator the workorder intends; (2) ED-c is in fact nonzero -- ' +
      'the antiunitary -1’ imposes T = +T on the polar c-type tensor (factor = ' +
      'trFactor(-1) * inversion-parity((-1)^3 = -1) = +1), the same magnetoelectric ' +
      'mechanism as the canonical Cr2O3 \'-3\'m\'\' fixture at the top of this file. ED-c is ' +
      'therefore the correct decisive, frame-sensitive pin: it takes the \'-42m\'-default ' +
      "(diagonal-mirror) J3 form post-fix, vs. the Rz(45 deg)-rotated ('-4m2'-axis) form " +
      'pre-fix.',
  },
  {
    group: "4'/m'm'm", tensor: 'ED', tr: 'i', setting: 2,
    expected: ['All components are zero.'],
    source: "4'/m'm'm has an antiunitary inversion (-1'); the time-even ED tensor vanishes in every setting (orientation-independent).",
    // VERIFY: pending human sign-off against the printed Birss tables.
  },
  {
    group: "4'/m'm'm", tensor: 'ED', tr: 'c', setting: 2,
    expected: ['\\chi_{xxz} = \\chi_{xzx} = -\\chi_{yyz} = -\\chi_{yzy}', '\\chi_{zxx} = -\\chi_{zyy}'],
    source: "Default 4'/m'm'm ED-c form (table-anchored, Table 4e via SIX_GENERATOR_FIX_DERIVATION: chi_xyz=chi_xzy=chi_yxz=chi_yzx, chi_zxy=chi_zyx) rotated by Rz(45deg) into the 4'/m'mm' setting. Pure tensor algebra; independent projection over the transformed operators reproduces it.",
    // VERIFY: pending human sign-off against the printed Birss tables.
  },
];
