/**
 * tensorForms.ts -- generalized symmetry-reduced tensor forms (Tables feature, Phase 1 engine).
 *
 * `computeTensorForm(group, setting, spec)` returns the independent-component form of an arbitrary
 * property tensor (rank 0-4, polar/axial, i/c, with an optional intrinsic index symmetry) for a
 * magnetic point group, in the SAME symbolic relation format the golden fixtures use
 * (`\chi_{xxx} = -\chi_{xyy}`, ...). It is a strict generalization of
 * `tensorProjection.calculateTensorBasisResults` (which is hardwired to rank-3/4, jk-symmetric,
 * ED/MD/EQ): it reuses the exact same rank-general projection primitives (`averageTensor` -- the
 * `det(R)` axial factor and the antiunitary time-odd sign already live there) and the same
 * independent-basis reduction, only parametrized by a `TensorSpec` instead of a `TensorType`.
 *
 * For `spec = {rank, parity, timeParity, intrinsic: 'jk'}` at rank 3/4 this reproduces
 * `calculateTensorBasisResults` component-for-component (asserted in `tensorForms.test.ts`); the
 * ED/MD/EQ paths are NOT modified, only reused. No new symbolic pipeline is introduced.
 *
 * @see docs/planning/DESIGN-tables-feature.md (locked design, engine section)
 * @see docs/references/BIRSS-APP-CONVENTIONS-REFERENCE.md (projection & particularization)
 */

import {
  EPSILON,
  GENERATORS,
  getCachedFullGroup,
  getTransformedGenerators,
  getAlternateSettings,
  det,
  type Matrix3x3,
} from './symmetryGroups';
import { getIndices, formatReducedRelations } from './tensorProjection';
import { isIndependentOf, rref, spanRank } from './linalg';

export type TensorRank = 0 | 1 | 2 | 3 | 4;
export type TensorParity = 'polar' | 'axial';
export type TensorTimeParity = 'i' | 'c';
/** Intrinsic index-permutation symmetry. `ij` = swap the first two indices; `jk` = swap the last two
 * (the ED/MD/EQ SHG particularization); `ij_kl` = rank-4 pair symmetries only -- each pair symmetric
 * with NO exchange between the pairs (e.g. the photoelastic tensor); `voigt` = rank-4 full Voigt
 * symmetry, i.e. `ij_kl` plus the pair exchange (ij <-> kl). */
export type TensorIntrinsic = 'none' | 'ij' | 'jk' | 'ij_kl' | 'voigt';

export interface TensorSpec {
  rank: TensorRank;
  parity: TensorParity;
  timeParity: TensorTimeParity;
  intrinsic: TensorIntrinsic;
}

export interface TensorForm {
  /** The independent, symmetry-averaged basis vectors (each length 3^rank), as a MINIMAL basis --
   * `basisResults.length` is the true independent-component count. Empty when the tensor vanishes
   * identically. */
  basisResults: number[][];
  rank: number;
  /** The symbolic relation strings: one proportionality chain per class
   * (`\chi_{xxx} = -\chi_{xyy}`, ...) followed by any residual composite relation
   * (`\chi_{xxxx} = \chi_{xxyy} + \chi_{xyxy} + \chi_{xyyx}`, Birss's printed sum-cell form). The
   * count therefore exceeds `basisResults.length` exactly when composites are present.
   * `['Identically zero.']` when `isZero`. */
  relations: string[];
  /** True iff the tensor has no surviving independent component for this group/setting/spec. */
  isZero: boolean;
}

/**
 * Index-permutation generators for an intrinsic symmetry, as position-remap arrays (`out[k]` names
 * the source position feeding output position `k`). Generators that do not apply at this rank
 * (e.g. `voigt` at rank != 4, `ij`/`jk` at rank < 2) contribute nothing -> identity only.
 */
function intrinsicGenerators(rank: number, intrinsic: TensorIntrinsic): number[][] {
  const id = Array.from({ length: rank }, (_, k) => k);
  const swap = (a: number, b: number): number[] => {
    const p = [...id];
    p[a] = b;
    p[b] = a;
    return p;
  };
  switch (intrinsic) {
    case 'ij':
      return rank >= 2 ? [swap(0, 1)] : [];
    case 'jk':
      return rank >= 2 ? [swap(rank - 2, rank - 1)] : [];
    case 'ij_kl':
      // Rank-4 pairs-only: each pair individually symmetric, NO pair exchange (e.g. the photoelastic
      // / electrostriction index symmetry -- a general, not symmetric, 6x6 Voigt matrix).
      return rank === 4
        ? [
            [1, 0, 2, 3],
            [0, 1, 3, 2],
          ]
        : [];
    case 'voigt':
      // Rank-4 pair symmetry: swap within pair (0,1), swap within pair (2,3), exchange the pairs.
      return rank === 4
        ? [
            [1, 0, 2, 3],
            [0, 1, 3, 2],
            [2, 3, 0, 1],
          ]
        : [];
    case 'none':
    default:
      return [];
  }
}

/** Flat index of the component obtained by applying position-remap `perm` to component `idx`. */
function permuteIndex(idx: number, rank: number, perm: number[]): number {
  const indices = getIndices(idx, rank);
  let out = 0;
  for (let k = 0; k < rank; k++) {
    out += indices[perm[k]] * Math.pow(3, rank - 1 - k);
  }
  return out;
}

/** The orbit of flat index `idx` under the group generated by `gens` (BFS closure). */
function indexOrbit(idx: number, rank: number, gens: number[][]): number[] {
  if (gens.length === 0) return [idx];
  const seen = new Set<number>([idx]);
  const stack = [idx];
  while (stack.length) {
    const cur = stack.pop()!;
    for (const g of gens) {
      const n = permuteIndex(cur, rank, g);
      if (!seen.has(n)) {
        seen.add(n);
        stack.push(n);
      }
    }
  }
  return [...seen];
}

/**
 * Formats a minimal basis into its relation set. The builder is shared with
 * `latexFormatting.calculateTensorComponentsView` via `tensorProjection.formatReducedRelations`
 * (Wave-2 E5; Q0 replaced the per-basis-vector builder with the proportionality-class + composite
 * one), so `{...,jk}` output equals `calculateTensorComponents` by construction.
 */
function formatFormRelations(basisResults: number[][], rank: number): string[] {
  if (basisResults.length === 0) return ['Identically zero.'];
  // Rank 0 has no index label, so its single surviving scalar is the sentinel `\chi`.
  if (rank === 0) return basisResults.map(() => '\\chi');
  const output = formatReducedRelations(basisResults, rank);
  return output.length > 0 ? output : ['Identically zero.'];
}

/** Base-3 digit decomposition of every flat index, precomputed once per rank. Same result as calling
 * `getIndices(idx, rank)` per index, but without the per-call array allocation that dominates the
 * rank-4 projection profile (getIndices was ~64M allocations per 122-group sweep). */
const digitTableCache = new Map<number, Uint8Array[]>();
function digitTable(rank: number): Uint8Array[] {
  const cached = digitTableCache.get(rank);
  if (cached) return cached;
  const dim = Math.pow(3, rank);
  const table = new Array<Uint8Array>(dim);
  for (let idx = 0; idx < dim; idx++) {
    const d = new Uint8Array(rank);
    let temp = idx;
    for (let i = rank - 1; i >= 0; i--) {
      d[i] = temp % 3;
      temp = Math.floor(temp / 3);
    }
    table[idx] = d;
  }
  digitTableCache.set(rank, table);
  return table;
}

interface FlatOp {
  /** row-major flattened 3x3 operation matrix (m[3a+b]) */
  m: Float64Array;
  det: number;
  anti: boolean;
}
/** Per-group flattened operation matrices (with det and antiunitary flag), computed once and reused
 * across every seed and every spec. Keyed by the cached full-group array identity (stable per
 * group/setting via getCachedFullGroup), so the flattening cost is paid once per group, not per seed. */
let flatOpCache = new WeakMap<Matrix3x3[], FlatOp[]>();
function flatOps(group: Matrix3x3[]): FlatOp[] {
  const cached = flatOpCache.get(group);
  if (cached) return cached;
  const ops = group.map((g) => {
    const m = g.m;
    return {
      m: Float64Array.of(m[0][0], m[0][1], m[0][2], m[1][0], m[1][1], m[1][2], m[2][0], m[2][1], m[2][2]),
      det: det(g),
      anti: g.isAntiUnitary === true,
    };
  });
  flatOpCache.set(group, ops);
  return ops;
}

/**
 * The independent, symmetry-averaged basis vectors for `spec` over `group` (already the full,
 * setting-transformed magnetic group with antiunitary flags). Generalizes
 * `calculateTensorBasisResults`: `rank`/`isAxial`/`isTimeOdd` come from the spec, and the
 * intrinsic index symmetry is applied by symmetrizing each seed over its index orbit before the
 * group average (instead of the hardwired last-two-index swap).
 *
 * The returned basis is MINIMAL (see the RREF note at the end of the function).
 *
 * The symmetry average is inlined here as an allocation-free flat-array projection (identical math
 * to `averageTensor(seed, ...)` -- averaged[out] = (1/N) Σ_op sign(op) Σ_{s∈orbit} Π_r m_op[out_r][s_r]
 * -- but ~2 orders of magnitude fewer allocations at rank 4). The shared `averageTensor` /
 * `transformTensor` in tensorProjection.ts are intentionally left unchanged so the ED/MD/EQ and
 * symbolic paths keep their exact existing behaviour.
 */
function computeBasis(group: Matrix3x3[], spec: TensorSpec): number[][] {
  const { rank, parity, timeParity, intrinsic } = spec;
  const isAxial = parity === 'axial';
  const isTimeOdd = timeParity === 'c';
  const dim = Math.pow(3, rank);
  const gens = intrinsicGenerators(rank, intrinsic);

  const digits = digitTable(rank);
  const ops = flatOps(group);
  const invN = 1 / group.length;

  const basisResults: number[][] = [];
  for (let i = 0; i < dim; i++) {
    const orbit = indexOrbit(i, rank, gens);
    // Process each intrinsic orbit once, from its minimal member (mirrors the `i > swappedIdx`
    // skip in calculateTensorBasisResults for the jk case).
    if (i !== Math.min(...orbit)) continue;

    // Flat, allocation-free symmetry average of the intrinsic-symmetric unit seed on `orbit`.
    const averaged = new Float64Array(dim);
    for (const op of ops) {
      const sign = (isAxial ? op.det : 1) * (isTimeOdd && op.anti ? -1 : 1);
      const m = op.m;
      for (let out = 0; out < dim; out++) {
        const dOut = digits[out];
        let acc = 0;
        for (const s of orbit) {
          const dS = digits[s];
          let p = 1;
          for (let r = 0; r < rank; r++) p *= m[dOut[r] * 3 + dS[r]];
          acc += p;
        }
        averaged[out] += sign * acc;
      }
    }
    for (let k = 0; k < dim; k++) averaged[k] *= invN;

    let allZero = true;
    for (let k = 0; k < dim; k++) {
      if (Math.abs(averaged[k]) >= EPSILON) {
        allZero = false;
        break;
      }
    }
    if (allZero) continue;

    if (isIndependentOf(averaged, basisResults, dim, EPSILON)) basisResults.push(Array.from(averaged));
  }
  // Q0: the proportionality dedup above leaves NON-MINIMAL spanning sets for the coupled rank-4
  // blocks of the 3-/6-fold groups (it cannot see multi-vector dependencies such as
  // chain2 + chain4 + chain5 = 3*chain1). RREF makes the basis minimal and canonical, so the pivots
  // name the free parameters unambiguously and the relation formatter can separate proportionality
  // classes from genuine composite relations. Rank-derived counts (spanRank) were always correct and
  // are unchanged. The reduction is gated on MINIMALITY (`length === spanRank`), not on the tensor
  // rank, so already-minimal cells stay BIT-identical: RREF's extra eliminations would otherwise
  // perturb the last bits (enough to tip a display rounding boundary on the irrational trigonal
  // entries).
  return basisResults.length === spanRank(basisResults) ? basisResults : rref(basisResults, dim);
}

function specKey(spec: TensorSpec): string {
  return `${spec.rank}:${spec.parity}:${spec.timeParity}:${spec.intrinsic}`;
}

const formCache = new Map<string, TensorForm | null>();

/**
 * The symmetry-reduced form of an arbitrary property tensor for a magnetic point group.
 * Returns `null` for an unknown group key (no GENERATORS entry).
 */
export function computeTensorForm(groupName: string, setting: number, spec: TensorSpec): TensorForm | null {
  const cacheKey = `${groupName}::setting${setting}::${specKey(spec)}`;
  const cached = formCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const generators = setting > 1 ? getTransformedGenerators(groupName, setting) : GENERATORS[groupName];
  if (!generators || generators.length === 0) {
    formCache.set(cacheKey, null);
    return null;
  }

  const groupCacheKey = setting > 1 ? `${groupName}::setting${setting}` : groupName;
  const group = getCachedFullGroup(groupCacheKey, generators);

  const basisResults = computeBasis(group, spec);
  const form: TensorForm = {
    basisResults,
    rank: spec.rank,
    relations: formatFormRelations(basisResults, spec.rank),
    isZero: basisResults.length === 0,
  };
  formCache.set(cacheKey, form);
  return form;
}

/**
 * A canonical, hashable normal form of the relation set for `(group, setting, spec)` -- the design
 * hook for the deferred "groups sharing this form" overview (a groupBy over 122 signatures). Two
 * groups whose tensors have the identical independent-component structure (same surviving
 * components, same equality/sign relations, up to overall basis ordering and normalization) get
 * the same signature. Returns `'unsupported'` for an unknown group and `'zero'` for a vanishing
 * tensor.
 */
export function getFormSignature(groupName: string, setting: number, spec: TensorSpec): string {
  const form = computeTensorForm(groupName, setting, spec);
  if (form === null) return 'unsupported';
  if (form.isZero) return `r${spec.rank}:zero`;
  const dim = Math.pow(3, spec.rank);

  const perBasis = form.basisResults.map((basis) => {
    let leadIdx = -1;
    const entries: string[] = [];
    for (let i = 0; i < dim; i++) {
      if (Math.abs(basis[i]) > EPSILON) {
        if (leadIdx === -1) leadIdx = i;
        const ratio = basis[i] / basis[leadIdx];
        entries.push(`${i}:${ratio.toFixed(6)}`);
      }
    }
    return entries.join(',');
  });

  perBasis.sort();
  return `r${spec.rank}|${perBasis.join('|')}`;
}

/**
 * A frame-canonical form signature for the "groups sharing this form" feature: the lexicographic
 * minimum of `getFormSignature` over every setting the app already tabulates for the group
 * (`ALTERNATE_SETTINGS`; setting 1 if none). Two groups share a form iff they share this signature.
 *
 * This is the printed-table notion of "same form": Birss/ITC choose, per group, the setting whose
 * components match the tabulated block matrix (e.g. ITC prints the bracketed alternate `2'mm' [m2'm']`
 * for block F5). Taking the min over the app's own S·G·S⁻¹ settings reproduces that choice without
 * any new O(3) canonicalization -- the setting machinery already produces exactly these frames. The
 * plain (frame-specific) `getFormSignature` is a strict refinement of this; see
 * `docs/findings/ANALYSIS-table-4b-4d-semantics.md` §9.
 */
const canonicalSignatureCache = new Map<string, string>();

/** Bench/test-only: clear every projection memoization cache (form/signature results plus the
 * per-rank digit tables and per-group flattened ops of the hot path) so a genuinely cold projection
 * can be measured. Not used by the app; results are unaffected. */
export function _clearTensorFormCaches(): void {
  formCache.clear();
  canonicalSignatureCache.clear();
  digitTableCache.clear();
  flatOpCache = new WeakMap<Matrix3x3[], FlatOp[]>();
}

export function getCanonicalFormSignature(groupName: string, spec: TensorSpec): string {
  const cacheKey = `${groupName}::${specKey(spec)}`;
  const cached = canonicalSignatureCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const alts = getAlternateSettings(groupName);
  const nSettings = alts ? alts.length + 1 : 1;
  let best: string | null = null;
  for (let s = 1; s <= nSettings; s++) {
    const sig = getFormSignature(groupName, s, spec);
    if (best === null || sig < best) best = sig;
  }
  const result = best ?? 'unsupported';
  canonicalSignatureCache.set(cacheKey, result);
  return result;
}
