/**
 * tensorForms.ts -- generalized symmetry-reduced tensor forms (Tables feature, Phase 1 engine).
 *
 * `computeTensorForm(group, setting, spec)` returns the independent-component form of an arbitrary
 * property tensor (rank 0-4, polar/axial, i/c, with an optional intrinsic index symmetry) for a
 * magnetic point group, in the SAME symbolic relation format the golden fixtures use
 * (`\chi_{xxx} = -\chi_{xyy}`, ...). It is a strict generalization of
 * `tensorProjection.calculateTensorBasisResults` (which is hardwired to rank-3/4, jk-symmetric,
 * ED/MD/EQ): it reuses the exact same rank-general projection primitives (`averageTensor` -- the
 * `det(R)` axial factor and the antiunitary time-odd sign already live there) and the same
 * independent-basis reduction, only parametrized by a `TensorSpec` instead of a `TensorType`.
 *
 * For `spec = {rank, parity, timeParity, intrinsic: 'jk'}` at rank 3/4 this reproduces
 * `calculateTensorBasisResults` component-for-component (asserted in `tensorForms.test.ts`); the
 * ED/MD/EQ paths are NOT modified, only reused. No new symbolic pipeline is introduced.
 *
 * @see docs/planning/DESIGN-tables-feature.md (locked design, engine section)
 * @see docs/references/BIRSS-APP-CONVENTIONS-REFERENCE.md (projection & particularization)
 */

import { EPSILON, GENERATORS, getCachedFullGroup, getTransformedGenerators, getAlternateSettings, type Matrix3x3 } from './symmetryGroups';
import { averageTensor, getIndices, getLabel, formatCoeff } from './tensorProjection';

export type TensorRank = 0 | 1 | 2 | 3 | 4;
export type TensorParity = 'polar' | 'axial';
export type TensorTimeParity = 'i' | 'c';
/** Intrinsic index-permutation symmetry (v1 set). `ij` = swap first two indices; `jk` = swap last
 * two (the ED/MD/EQ SHG particularization); `voigt` = rank-4 pair symmetry. */
export type TensorIntrinsic = 'none' | 'ij' | 'jk' | 'voigt';

export interface TensorSpec {
  rank: TensorRank;
  parity: TensorParity;
  timeParity: TensorTimeParity;
  intrinsic: TensorIntrinsic;
}

export interface TensorForm {
  /** The independent, symmetry-averaged basis vectors (each length 3^rank). Empty when the tensor
   * vanishes identically. */
  basisResults: number[][];
  rank: number;
  /** The symbolic relation strings (`\chi_{xxx} = -\chi_{xyy}`, ...), one per independent basis
   * vector. `['Identically zero.']` when `isZero`. */
  relations: string[];
  /** True iff the tensor has no surviving independent component for this group/setting/spec. */
  isZero: boolean;
}

/**
 * Index-permutation generators for an intrinsic symmetry, as position-remap arrays (`out[k]` names
 * the source position feeding output position `k`). Generators that do not apply at this rank
 * (e.g. `voigt` at rank != 4, `ij`/`jk` at rank < 2) contribute nothing -> identity only.
 */
function intrinsicGenerators(rank: number, intrinsic: TensorIntrinsic): number[][] {
  const id = Array.from({ length: rank }, (_, k) => k);
  const swap = (a: number, b: number): number[] => {
    const p = [...id];
    p[a] = b;
    p[b] = a;
    return p;
  };
  switch (intrinsic) {
    case 'ij':
      return rank >= 2 ? [swap(0, 1)] : [];
    case 'jk':
      return rank >= 2 ? [swap(rank - 2, rank - 1)] : [];
    case 'voigt':
      // Rank-4 pair symmetry: swap within pair (0,1), swap within pair (2,3), exchange the pairs.
      return rank === 4 ? [[1, 0, 2, 3], [0, 1, 3, 2], [2, 3, 0, 1]] : [];
    case 'none':
    default:
      return [];
  }
}

/** Flat index of the component obtained by applying position-remap `perm` to component `idx`. */
function permuteIndex(idx: number, rank: number, perm: number[]): number {
  const indices = getIndices(idx, rank);
  let out = 0;
  for (let k = 0; k < rank; k++) {
    out += indices[perm[k]] * Math.pow(3, rank - 1 - k);
  }
  return out;
}

/** The orbit of flat index `idx` under the group generated by `gens` (BFS closure). */
function indexOrbit(idx: number, rank: number, gens: number[][]): number[] {
  if (gens.length === 0) return [idx];
  const seen = new Set<number>([idx]);
  const stack = [idx];
  while (stack.length) {
    const cur = stack.pop()!;
    for (const g of gens) {
      const n = permuteIndex(cur, rank, g);
      if (!seen.has(n)) {
        seen.add(n);
        stack.push(n);
      }
    }
  }
  return [...seen];
}

/**
 * Formats independent basis vectors into equality/sign relation strings, identical in form to
 * `latexFormatting.formatResults` (kept in lockstep so `{...,jk}` output equals
 * `calculateTensorComponents`). Rank 0 has no index label, so its single surviving scalar is
 * reported as the sentinel `\chi` (a bare, allowed scalar) rather than an empty `\chi_{}`.
 */
function formatFormRelations(basisResults: number[][], rank: number): string[] {
  if (basisResults.length === 0) return ['Identically zero.'];
  const dim = Math.pow(3, rank);
  const output: string[] = [];

  for (const basis of basisResults) {
    if (rank === 0) {
      output.push('\\chi'); // scalar: allowed (nonzero invariant); no index label exists
      continue;
    }
    const members: string[] = [];
    let leadIdx = -1;
    const addedLabels = new Set<string>();

    for (let i = 0; i < dim; i++) {
      if (Math.abs(basis[i]) > EPSILON) {
        const label = getLabel(getIndices(i, rank));
        if (addedLabels.has(label)) continue;
        addedLabels.add(label);

        if (leadIdx === -1) leadIdx = i;
        const scale = basis[i] / basis[leadIdx];
        const sign = scale > 0 ? (members.length === 0 ? '' : ' = ') : ' = -';
        const scaleStr = formatCoeff(scale);
        members.push(`${sign}${scaleStr}${label}`);
      }
    }
    if (members.length > 0) output.push(members.join(''));
  }
  return output.length > 0 ? output : ['Identically zero.'];
}

/**
 * The independent, symmetry-averaged basis vectors for `spec` over `group` (already the full,
 * setting-transformed magnetic group with antiunitary flags). Generalizes
 * `calculateTensorBasisResults`: `rank`/`isAxial`/`isTimeOdd` come from the spec, and the
 * intrinsic index symmetry is applied by symmetrizing each seed over its index orbit before the
 * group average (instead of the hardwired last-two-index swap).
 */
function computeBasis(group: Matrix3x3[], spec: TensorSpec): number[][] {
  const { rank, parity, timeParity, intrinsic } = spec;
  const isAxial = parity === 'axial';
  const isTimeOdd = timeParity === 'c';
  const dim = Math.pow(3, rank);
  const gens = intrinsicGenerators(rank, intrinsic);

  const basisResults: number[][] = [];
  for (let i = 0; i < dim; i++) {
    const orbit = indexOrbit(i, rank, gens);
    // Process each intrinsic orbit once, from its minimal member (mirrors the `i > swappedIdx`
    // skip in calculateTensorBasisResults for the jk case).
    if (i !== Math.min(...orbit)) continue;

    const seed = new Array(dim).fill(0);
    for (const m of orbit) seed[m] = 1; // intrinsic-symmetric seed

    const averaged = averageTensor(seed, group, rank, isAxial, isTimeOdd);

    if (averaged.every(v => Math.abs(v) < EPSILON)) continue;

    let isNew = true;
    for (const existing of basisResults) {
      let ratio = 0;
      let match = true;
      for (let k = 0; k < dim; k++) {
        if (Math.abs(existing[k]) > EPSILON) {
          const r = averaged[k] / existing[k];
          if (ratio === 0) ratio = r;
          else if (Math.abs(r - ratio) > EPSILON) {
            match = false;
            break;
          }
        } else if (Math.abs(averaged[k]) > EPSILON) {
          match = false;
          break;
        }
      }
      if (match) {
        isNew = false;
        break;
      }
    }
    if (isNew) basisResults.push(averaged);
  }
  return basisResults;
}

function specKey(spec: TensorSpec): string {
  return `${spec.rank}:${spec.parity}:${spec.timeParity}:${spec.intrinsic}`;
}

const formCache = new Map<string, TensorForm | null>();

/**
 * The symmetry-reduced form of an arbitrary property tensor for a magnetic point group.
 * Returns `null` for an unknown group key (no GENERATORS entry).
 */
export function computeTensorForm(groupName: string, setting: number, spec: TensorSpec): TensorForm | null {
  const cacheKey = `${groupName}::setting${setting}::${specKey(spec)}`;
  const cached = formCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const generators = setting > 1 ? getTransformedGenerators(groupName, setting) : GENERATORS[groupName];
  if (!generators || generators.length === 0) {
    formCache.set(cacheKey, null);
    return null;
  }

  const groupCacheKey = setting > 1 ? `${groupName}::setting${setting}` : groupName;
  const group = getCachedFullGroup(groupCacheKey, generators);

  const basisResults = computeBasis(group, spec);
  const form: TensorForm = {
    basisResults,
    rank: spec.rank,
    relations: formatFormRelations(basisResults, spec.rank),
    isZero: basisResults.length === 0,
  };
  formCache.set(cacheKey, form);
  return form;
}

/**
 * A canonical, hashable normal form of the relation set for `(group, setting, spec)` -- the design
 * hook for the deferred "groups sharing this form" overview (a groupBy over 122 signatures). Two
 * groups whose tensors have the identical independent-component structure (same surviving
 * components, same equality/sign relations, up to overall basis ordering and normalization) get
 * the same signature. Returns `'unsupported'` for an unknown group and `'zero'` for a vanishing
 * tensor.
 */
export function getFormSignature(groupName: string, setting: number, spec: TensorSpec): string {
  const form = computeTensorForm(groupName, setting, spec);
  if (form === null) return 'unsupported';
  if (form.isZero) return `r${spec.rank}:zero`;
  const dim = Math.pow(3, spec.rank);

  const perBasis = form.basisResults.map(basis => {
    let leadIdx = -1;
    const entries: string[] = [];
    for (let i = 0; i < dim; i++) {
      if (Math.abs(basis[i]) > EPSILON) {
        if (leadIdx === -1) leadIdx = i;
        const ratio = basis[i] / basis[leadIdx];
        entries.push(`${i}:${ratio.toFixed(6)}`);
      }
    }
    return entries.join(',');
  });

  perBasis.sort();
  return `r${spec.rank}|${perBasis.join('|')}`;
}

/**
 * A frame-canonical form signature for the "groups sharing this form" feature: the lexicographic
 * minimum of `getFormSignature` over every setting the app already tabulates for the group
 * (`ALTERNATE_SETTINGS`; setting 1 if none). Two groups share a form iff they share this signature.
 *
 * This is the printed-table notion of "same form": Birss/ITC choose, per group, the setting whose
 * components match the tabulated block matrix (e.g. ITC prints the bracketed alternate `2'mm' [m2'm']`
 * for block F5). Taking the min over the app's own S·G·S⁻¹ settings reproduces that choice without
 * any new O(3) canonicalization -- the setting machinery already produces exactly these frames. The
 * plain (frame-specific) `getFormSignature` is a strict refinement of this; see
 * `docs/findings/ANALYSIS-table-4b-4d-semantics.md` §9.
 */
const canonicalSignatureCache = new Map<string, string>();

export function getCanonicalFormSignature(groupName: string, spec: TensorSpec): string {
  const cacheKey = `${groupName}::${specKey(spec)}`;
  const cached = canonicalSignatureCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const alts = getAlternateSettings(groupName);
  const nSettings = alts ? alts.length + 1 : 1;
  let best: string | null = null;
  for (let s = 1; s <= nSettings; s++) {
    const sig = getFormSignature(groupName, s, spec);
    if (best === null || sig < best) best = sig;
  }
  const result = best ?? 'unsupported';
  canonicalSignatureCache.set(cacheKey, result);
  return result;
}
