// Generator for src/data/sharingPartitions.ts (npm run sharingdata).
//
// vitest 4 no longer ships the standalone `vite-node` binary, so we drive the TS partition library
// through Vite's SSR module loader (the already-installed `vite` dependency -- no new dependency,
// same offline `node scripts/*.mjs` pattern as the table-7 codegen). The partition logic itself
// lives in scripts/sharingPartitionLib.ts and is shared with the drift-guard test.
import { createServer } from 'vite';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const here = path.dirname(fileURLToPath(import.meta.url));

const server = await createServer({
  configFile: false,
  root: path.resolve(here, '..'),
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
});

let partitions;
try {
  const lib = await server.ssrLoadModule(path.resolve(here, 'sharingPartitionLib.ts'));
  partitions = lib.buildAllPartitions();
} finally {
  await server.close();
}

const header = `// DO NOT EDIT -- generated by scripts/generate-sharing.mjs (npm run sharingdata).
//
// Precomputed "groups sharing this form" partitions. For every UI-reachable tensor spec
// (rank x parity x timeParity x the valid intrinsics -- see src/data/uiTensorSpecs.ts), this is the
// frame-canonical-signature partition of all 122 point groups: each class is a list of group names
// (in POINT_GROUPS order), and every group appears in exactly one class. The Tables page looks up
// the class containing the selected group in O(1) instead of running the 122-group signature sweep
// on the main thread. Regenerate after any change to the tensor-form engine or the group registry;
// sharingPartitions.reference.test.ts guards this file against drift.
`;

const body = Object.entries(partitions)
  .map(([key, classes]) => {
    const cls = classes.map((c) => `    [${c.map((n) => JSON.stringify(n)).join(', ')}]`).join(',\n');
    return `  ${JSON.stringify(key)}: [\n${cls},\n  ],`;
  })
  .join('\n');

const content = `${header}
export const SHARING_PARTITIONS: Record<string, string[][]> = {
${body}
};
`;

const outPath = path.resolve(here, '../src/data/sharingPartitions.ts');
writeFileSync(outPath, content, 'utf8');
console.log(`Wrote ${outPath} (${Object.keys(partitions).length} specs)`);
